# Button cards location
button_card_templates: !include_dir_merge_named "custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"
views:
  - title: Home
    type: custom:horizontal-layout
    layout_type: custom:horizontal-layout
    layout:
      width: 400
      max_cols: 1
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: chip_temperature
            variables:
              ulm_chip_temperature_inside: sensor.thermostat_temperature
              ulm_chip_temperature_outside: sensor.dark_sky_temperature
              ulm_chip_temperature_weather: weather.dark_sky
          - type: 'custom:button-card'
            template: chip_presence_detection
            variables:
              ulm_chip_presence_counter_residents: sensor.double_take_office
              ulm_chip_presence_counter_guests: sensor.double_take_lounge
          - type: 'custom:button-card'
            template: chip_power_consumption
            variables:
              ulm_chip_electric_consumption: sensor.ovo_last_electricity_reading
              ulm_chip_electric_price: sensor.ovo_last_electricity_cost
          - type: 'custom:button-card'
            template: chip_alarm
            entity: alarm_control_panel.alarm_panel
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.russell
              ulm_card_person_use_entity_picture: false
              ulm_card_person_zone1: work
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: custom_card_paddy_waste_collection
            entity: sensor.waste_collection_household
          - type: 'custom:button-card'
            template: custom_card_paddy_waste_collection
            entity: sensor.waste_collection_recycling
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Lighting
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light_slider_collapse
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_enable_horizontal: false
              ulm_card_light_name: Bathroom
            entity: light.bathroom_light
            name: Bathroom
          - type: 'custom:button-card'
            template: card_light_slider_collapse
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_enable_horizontal: false
              ulm_card_light_name: Bedroom
            entity: light.bedroom_light
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light_slider_collapse
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_enable_horizontal: false
            entity: light.hallway
          - type: 'custom:button-card'
            template: card_light_slider_collapse
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_enable_horizontal: false
              ulm_card_light_name: Landing
            entity: light.landing_light
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_light_slider_collapse
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_enable_horizontal: false
              ulm_card_light_name: Lounge
            entity: light.lounge_light
          - type: 'custom:button-card'
            template: card_light_slider_collapse
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_color: true
              ulm_card_light_enable_horizontal: false
              ulm_card_light_name: Office
            entity: light.office_light
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Plugs
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_power_outlet
            entity: switch.sonoff_s26_1_relay
            name: Ambient
          - type: 'custom:button-card'
            template: card_power_outlet
            entity: switch.sonoff_s26_2_relay
            name: Clock
          - type: 'custom:button-card'
            template: card_power_outlet
            entity: switch.smart_plug
            name: Subwoofer
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Media
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_media_player_with_controls
            variables:
              ulm_card_media_player_with_controls_name: "Livingroom Shield"
              ulm_card_media_player_with_controls_entity: media_player.living_room_nvidia_shield
          - type: custom:button-card
            template: edge

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Climate
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          # - type: 'custom:button-card'
          #   template: custom_card_paddy_welcome_with_weather
          #   variables:
          #     ulm_custom_card_paddy_welcome_time: sensor.time
          #     ulm_custom_card_paddy_welcome_weather_provider: weather.dark_sky
          - type: "custom:button-card"
            template: card_weather
            entity: weather.dark_sky
            variables:
              ulm_card_weather_name: " "
              ulm_card_weather_primary_info:
                - wind_speed
                - precipitation_probability
              ulm_card_weather_backdrop:
                fade: true
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge     
        - type: 'custom:button-card'
          template:
            - card_thermostat
          variables:
            ulm_card_thermostat_sensor: sensor.thermostat_temperature
          entity: climate.heating_controller
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge     
        - type: 'custom:button-card'
          template: card_graph
          variables:
            ulm_card_graph_color: "var(--google-blue)"
            ulm_card_graph_name: Temperature thermostat
            ulm_card_graph_entity: sensor.thermostat_temperature       
        - type: 'custom:button-card'
          template: card_graph
          variables:
            ulm_card_graph_color: "var(--google-blue)"
            ulm_card_graph_name: Temperature office
            ulm_card_graph_entity: sensor.bme680_temperature
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge     
        - type: 'custom:button-card'
          template: card_graph
          variables:
            ulm_card_graph_color: "var(--google-blue)"
            ulm_card_graph_name: Temperature server room
            ulm_card_graph_entity: sensor.upstairs_temperature       
        - type: 'custom:button-card'
          template: card_graph
          variables:
            ulm_card_graph_color: "var(--google-blue)"
            ulm_card_graph_name: Temperature bedroom
            ulm_card_graph_entity: sensor.temperature_humidity_sensor_temperature
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge     
        - type: 'custom:button-card'
          template: card_graph
          variables:
            ulm_card_graph_color: "var(--google-blue)"
            ulm_card_graph_name: Temperature landing
            ulm_card_graph_entity: sensor.landing_temperature_2   
        - type: 'custom:button-card'
          template: card_graph
          variables:
            ulm_card_graph_color: "var(--google-blue)"
            ulm_card_graph_name: Humidity office
            ulm_card_graph_entity: sensor.bme680_humidity
        - type: custom:button-card
          template: edge
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_graph
          variables:
            ulm_card_graph_color: "var(--google-blue)"
            ulm_card_graph_name: Humidity server room
            ulm_card_graph_entity: sensor.upstairs_humidity   
        - type: 'custom:button-card'
          template: card_graph
          variables:
            ulm_card_graph_color: "var(--google-blue)"
            ulm_card_graph_name: Humidity bedroom
            ulm_card_graph_entity: sensor.temperature_humidity_sensor_humidity      
        - type: custom:button-card
          template: edge
  - title: Cameras
    type: custom:horizontal-layout
    layout_type: custom:horizontal-layout
    layout:
      width: 400
      max_cols: 1
    cards:
    - type: horizontal-stack
      cards:
        - type: custom:button-card
          template: edge
        - type: custom:button-card
          template: title
          name: Cameras
        - type: custom:button-card
          template: edge
    - type: horizontal-stack
      cards:
      - type: custom:button-card
        template: edge  
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.driveway
            name: driveway
            webrtc:
              url: rtsp://frigate:frigate1234@10.30.0.243:554/h264Preview_01_main
              live_provider: webrtc
        event_viewer:
          controls:
            thumbnails:
              mode: below
      - type: custom:button-card
        template: edge
    - type: horizontal-stack
      cards:
      - type: custom:button-card
        template: edge  
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.office
            webrtc:
              url: rtsp://frigate:frigate1234@10.30.0.244:554/h264Preview_01_main
              live_provider: webrtc
        event_viewer:
          controls:
            thumbnails:
              mode: below
      - type: custom:button-card
        template: edge
    - type: horizontal-stack
      cards:
      - type: custom:button-card
        template: edge  
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.lounge
            webrtc:
              url: rtsp://rtsp:frigate1234@10.30.0.111:554/av_stream/ch0
              live_provider: webrtc
        event_viewer:
          controls:
            thumbnails:
              mode: below
      - type: custom:button-card
        template: edge  
