- platform: darksky
  api_key: !secret darksky_apikey
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - wind_speed
    - humidity
- platform: template
  sensors:
    habitica_gold_round:
      value_template: "{{ states('sensor.habitica_russell_gp') | round(2) }}"
- platform: template
  sensors:
    habitica_hp_round:
      value_template: "{{ states('sensor.habitica_russell_hp') | round(2) }}"
- platform: template
  sensors:
    habitica_mp_round:
      value_template: "{{ states('sensor.habitica_russell_mp') | round(2) }}"
- platform: template
  sensors:
    habitica_level_perc:
      value_template: "{{ (states('sensor.habitica_russell_exp') | float / states('sensor.habitica_russell_tonextlevel') | float * 100) | round(2) }}"
      unit_of_measurement: "%"
- platform: template
  sensors:
    russell_home_status:
      friendly_name: 'Russell Home Status'
      value_template: "{{is_state('device_tracker.pixel_4a_3','home') or (is_state('device_tracker.pixel_4a_3','home') and is_state('device_tracker.pixel_4a','home'))}}"
- platform: template
  sensors:
    anyone_home:
      friendly_name: 'Home Status'
      value_template: "{% if is_state('sensor.russell_home_status', 'True')-%}home{%else%}not_home{% endif %}"
- platform: mqtt
  state_topic: 'monitor/first floor/russellpixel4'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'Russell Occupancy Confidence'
- platform: min_max
  name: "Home Occupancy Confidence"
  type: max
  round_digits: 0
  entity_ids:
    - sensor.russell_occupancy_confidence
- platform: mqtt
  state_topic: 'monitor/first floor/russellpixel4/rssi'
  unit_of_measurement: 'dBm'
  name: 'Russell Pixel 4 RSSI'