- platform: darksky
  api_key: !secret darksky_apikey
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - wind_speed
    - humidity
- platform: template
  sensors:
    russell_home_status:
      friendly_name: 'Russell Home Status'
      value_template: "{{is_state('device_tracker.pixel_4a_3','home') or (is_state('device_tracker.pixel_4a_3','home') and is_state('device_tracker.pixel_4a','home')) or (not is_state('sensor.pixel_4a_room_presence','not_home'))}}"
- platform: template
  sensors:
    anyone_home:
      friendly_name: 'Home Status'
      value_template: "{% if is_state('sensor.russell_home_status', 'True')-%}home{%else%}not_home{% endif %}"
